version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vinod
      MYSQL_USER: vinod
      MYSQL_PASSWORD: vinod
    ports:
      - "3306:3306"

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vinod
      SPRING_DATASOURCE_USERNAME: vinod
      SPRING_DATASOURCE_PASSWORD: vinod

#  docker exec -it mysql-container mysql -u vinod -p
# docker-compose up --build